name: Build

on:
  push:
    branches:
      - main 

jobs:
  build-container-chrome:
    runs-on: ubuntu-latest
    env:
      UPSTREAM_TAG: "1.15.0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./images/chrome/
          build-args: |-
            UPSTREAM_TAG=${{ env.UPSTREAM_TAG }}
          tags: bennycooly/kasmweb-chrome:${{ env.UPSTREAM_TAG }}
